blog/urls.py
from django.urls import path,include
from . import views
import jobs.views

urlpatterns = [
    path('',views.blog_home, name='blog_home'),
    path('<int:blog_id>/',views.detail,name='detail'),



]

jobs/urls.py
from django.urls import path,include
from . import views

urlpatterns = [

    path('',views.home, name='home')
    #path('blog/',include(('blog.urls','blog'),namespace='blog'))


]

portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import jobs.views




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',jobs.views.home, name='home'),
    path('blog/',include(('blog.urls','blog'),namespace='blog')),
    path('jobs/',include(('jobs.urls','jobs'),namespace='jobs')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255)
    pub_date=models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to='images/')
    
    class Meta:
        ordering = ['-pub_date']

    @property
    def summary(self):
        return self.body[:100]
    @property
    def pub_date_pretty(self):
        return self.pub_date.strftime('%b %e %Y')

    def __str__(self):
        return self.title

jobs/models.py
from django.db import models

# Create your models here.

class Job(models.Model):

    image=models.ImageField(upload_to='images/', blank=True)
    title =models.CharField(max_length=2000)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404

from .models import Post

# Create your views here.

def blog_home(request):
    posts = Post.objects
    return render(request,'blog/home.html',{'posts':posts})

def detail(request,blog_id):

    detailblog=get_object_or_404(Blog, pk=blog_id) #get particular object from database or return 404

    return render(request,'blog/detail.html',{'detailblog':detailblog})

jobs/views.py
from django.shortcuts import render

from .models import Job

# Create your views here.

def home(request):
    jobs = Job.objects
    return render(request,'jobs/home.html',{'jobs':jobs})

blog/templates/blog/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

blog/templates/blog/home.html
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <title>Home</title>

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>

</head>
<body>

  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-sm">
      <div class="container fluid">
        <a class="navbar-brand d-flex align-items-center" href="#">Mirel Voicu</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <div class="navbar-nav ms-auto">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="#">Linkedin</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Résumé</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'blog:blog_home' %}">Blog</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
  </header>

  <div class="container">

    <main>
      <h1 class = "text-center pt-3" >Welcome to my blog</h1>
      <br>
      <br>
      <h2>Latest posts</h2>
      <hr>

      {% for post in posts.all %}

      <div class="card mb-3" style="max-width: 2000px;">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="{{ post.image.url }}" class="img-fluid rounded-start" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{ post.title }}</h5>
              <p class="card-text">{{ post.summary }}...</p>
              <a href="#">Read more</a>
              <p class="card-text"><small class="text-muted">Last updated on {{ post.pub_date_pretty }}</small></p>
            </div>
          </div>
        </div>
      </div>

      {%endfor%}
    </main>

  </div>


  <footer class="text-muted py-5">
    <div class="container text-center">
      <p>©️ Mirel Voicu {% now "Y" %}</p>
    </div>
  </footer>

  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
-->
</body>
</html>

jobs/templates/jobs/home.html
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <title>Home</title>

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>

</head>
<body>

  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-sm">
      <div class="container fluid">
        <a class="navbar-brand d-flex align-items-center" href="#">Mirel Voicu</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <div class="navbar-nav ms-auto">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="#">Linkedin</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Résumé</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:blog_home' %}">Blog</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
  </header>

  <main>

    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-black">Hi, I'm Mirel</h1>
          <p class="lead text-muted"> I am a senior RAN planning and optimization engineer. I also like Python programming, SQL and automation.</p>
          <p>
            <a href="mailto:mirel.voicu02@gmail.com" class="btn btn-primary my-2">Send me an email</a>
          </p>
        </div>
      </div>
    </section>

    <div class="album py-5 bg-light">
      <div class="container">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

          {% for job in jobs.all %}
          <div class="col">
            <div class="card border-dark mb-3  shadow-sm">
              <img class="bd-placeholder-img  card-img-top " alt="No image" width="100%" height="225" src="{{ job.image.url }}">

              <div class="card-body" style="background-color: #f5f5f5">
                <p class="card-text">{{ job.title }}</p>
                <!-- <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                  </div>
                  <small class="text-muted">9 mins</small>
                </div> -->
              </div>
            </div>
          </div>
          {% endfor %}

        </div>
      </div>
    </div>

  </main>

  <footer class="text-muted py-5">
    <div class="container text-center">
      <p>©️ Mirel Voicu {% now "Y" %}</p>
    </div>
  </footer>

  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
-->
</body>
</html>